# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-Query
version:      0.03
version_from: lib/Geo/Query.pm
installdirs:  site
requires:
    Geo::Query::LatLong:           0
    Math::Trig:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
